apiVersion: cluster.x-k8s.io/v1beta2
kind: MachineDeployment
metadata:
  name: example-workers
  namespace: default
spec:
  replicas: 2 # Instead of 1
  clusterName: example
  selector:
    matchLabels:
      cluster: example
  template:
    metadata:
      labels:
        cluster: example
    spec:
      clusterName: example
      version: v1.34.0
      bootstrap:
        configRef:
          apiGroup: bootstrap.cluster.x-k8s.io
          kind: KubeadmConfigTemplate
          name: worker
      infrastructureRef:
        apiGroup: infrastructure.cluster.x-k8s.io
        kind: DockerMachineTemplate
        name: default-machine-template
