---
apiVersion: v1
kind: Namespace
metadata:
  name: docker-infrastructure-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: InfrastructureProvider
metadata:
  name: docker
  namespace: docker-infrastructure-system
spec:
  version: v1.12.3
